config/routes.rb
Rails.application.routes.draw do
  #root 'top#index'
  #root to: redirect('/top/index')
  root to: redirect('/girls')
  devise_for :kanrisyas
  get 'top/index'
  get 'aceess/index'
  resources :users
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :uses
  get 'event_view/index'
  resources :events
  resources :bookings
  resources :contacts, only: [:new, :create]
  get 'contacts/new'
  get 'waittime/index'
  get 'waittime/show'
  resources :yoyakus
  resources :reserves
  get 'system/index'
  resources :ryokins
  resources :systems
  get 'janitor/index'
  get 'newcomers/index'
  get 'plan/index'
  get 'plan/show'
  get 'girls/janitor'
  resources :options
  resources :option_lists
  resources :tags
  resources :schedules
  resources :data_pages
  resources :girls
  get 'contacts', to: 'contacts#new'
  get 'waittime', to: 'waittime#index'
  get 'event_view', to: 'event_view#index'
  get 'plan', to: 'plan#index'
  get 'plan/:work_day', to: 'plan#show'
  get 'newcomers', to: 'newcomers#index'
  get 'system', to: 'system#index'
  get 'janitor', to: 'janitor#index'
  get 'girls/janitor' , to: 'girls#janitor'
  get 'aceess', to: 'aceess#index'
  get 'top', to: 'top#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :girl
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/data_page.rb
class DataPage < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
    
end

app/models/girl.rb
class Girl < ApplicationRecord
    has_many :schedules, -> { order("work_day asc") }
    has_many :options
    has_many :yoyakus
    has_many :bookings
    has_one :tag
    mount_uploader :girl_picture, PictureUploader

    validates :name, presence: true
    validates :age, presence: true
    validates :height, presence: true
    validates :bust, presence: true
    validates :bust_cup, presence: true
    validates :hip, presence: true
    validates :message, presence: true
    validates :tag_a, presence: true
    validates :tag_b, presence: true
    validates :tag_c, presence: true
    validates :tag_d, presence: true
    validates :nomination_fee, presence: true
    validates :start_date, presence: true
    validates :experience, presence: true
    validates :option_id, presence: true





   
end

app/models/kanrisya.rb
class Kanrisya < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/option.rb
class Option < ApplicationRecord
    belongs_to :girl
    has_many :option_lists
    mount_uploader :o_picture, PictureUploader
end

app/models/option_list.rb
class OptionList < ApplicationRecord
    belongs_to :option
    mount_uploader :option_picture, PictureUploader
end

app/models/reserve.rb
class Reserve < ApplicationRecord
    belongs_to :girl
    belongs_to :schedule
    
end

app/models/ryokin.rb
class Ryokin < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    has_many :reserves
    belongs_to :girl

    validates :work_day, presence: true
  validates :start_time, presence: true
  validates :finish_time, presence: true
end

app/models/system.rb
class System < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    belongs_to :girl,optional: true
end

app/models/use.rb
class Use < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   #devise :database_authenticatable, :registerable,
     #     :recoverable, :rememberable, :validatable
end

app/models/yoyaku.rb
class Yoyaku < ApplicationRecord
belongs_to :girl

end

app/controllers/data_pages_controller.rb
class DataPagesController < ApplicationController
  before_action :set_data_page, only: %i[ show edit update destroy ]

  # GET /data_pages or /data_pages.json
  def index
    @data_pages = DataPage.page params[:page]
  end

  # GET /data_pages/1 or /data_pages/1.json
  def show
  end

  # GET /data_pages/new
  def new
    @data_page = DataPage.new
  end

  # GET /data_pages/1/edit
  def edit
  end

  # POST /data_pages or /data_pages.json
  def create
    @data_page = DataPage.new(data_page_params)

    respond_to do |format|
      if @data_page.save
        format.html { redirect_to data_page_url(@data_page), notice: "Data page was successfully created." }
        format.json { render :show, status: :created, location: @data_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @data_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_pages/1 or /data_pages/1.json
  def update
    respond_to do |format|
      if @data_page.update(data_page_params)
        format.html { redirect_to data_page_url(@data_page), notice: "Data page was successfully updated." }
        format.json { render :show, status: :ok, location: @data_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @data_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_pages/1 or /data_pages/1.json
  def destroy
    @data_page.destroy

    respond_to do |format|
      format.html { redirect_to data_pages_url, notice: "Data page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_page
      @data_page = DataPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def data_page_params
      params.require(:data_page).permit(:data)
    end
end

app/helpers/data_pages_helper.rb
module DataPagesHelper
end

app/helpers/girls_helper.rb
module GirlsHelper
end

app/helpers/plan_helper.rb
module PlanHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/uses_helper.rb
module UsesHelper
end

app/views/data_pages/_data_page.html.erb
<div id="<%= dom_id data_page %>">
  <p>
    <strong>Data:</strong>
    <%= data_page.data %>
  </p>

</div>

app/views/data_pages/_form.html.erb
<%= form_with(model: data_page) do |form| %>
  <% if data_page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(data_page.errors.count, "error") %> prohibited this data_page from being saved:</h2>

      <ul>
        <% data_page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.text_area :data %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/data_pages/edit.html.erb
<h1>Editing data page</h1>

<%= render "form", data_page: @data_page %>

<br>

<div>
  <%= link_to "Show this data page", @data_page %> |
  <%= link_to "Back to data pages", data_pages_path %>
</div>

app/views/data_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">Data Pages</h1>

<div class="mt-4 mb-4">
  <%= page_entries_info @data_pages %>
</div>

<table class="table">
<thead>
  <tr>
    <th>ID</th>
     <th>Data</th>
     <th>Created at</th>
     <th colspan="3"></th>
    </tr>
</thead>

<tbody>
<% @data_pages.each do |data_page| %>
  <tr>
    <td><%= data_page.id %></td>
    <td><%= data_page.data %></td>
    <td><%= data_page.created_at %></td>
  </tr>
<% end %>
</tbody>
</table>
<br>
<div><%= paginate @data_pages %></div>
<br>
<%= link_to 'New Data Page', new_data_page_path %>

app/views/data_pages/new.html.erb
<h1>New data page</h1>

<%= render "form", data_page: @data_page %>

<br>

<div>
  <%= link_to "Back to data pages", data_pages_path %>
</div>

app/views/data_pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @data_page %>

<div>
  <%= link_to "Edit this data page", edit_data_page_path(@data_page) %> |
  <%= link_to "Back to data pages", data_pages_path %>

  <%= button_to "Destroy this data page", @data_page, method: :delete %>
</div>