config/routes.rb
Rails.application.routes.draw do
  #root 'top#index'
  #root to: redirect('/top/index')
  root to: redirect('/girls')
  devise_for :kanrisyas
  get 'top/index'
  get 'aceess/index'
  resources :users
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :uses
  get 'event_view/index'
  resources :events
  resources :bookings
  resources :contacts, only: [:new, :create]
  get 'contacts/new'
  get 'waittime/index'
  get 'waittime/show'
  resources :yoyakus
  resources :reserves
  get 'system/index'
  resources :ryokins
  resources :systems
  get 'janitor/index'
  get 'newcomers/index'
  get 'plan/index'
  get 'plan/show'
  get 'girls/janitor'
  resources :options
  resources :option_lists
  resources :tags
  resources :schedules
  resources :data_pages
  resources :girls
  get 'contacts', to: 'contacts#new'
  get 'waittime', to: 'waittime#index'
  get 'event_view', to: 'event_view#index'
  get 'plan', to: 'plan#index'
  get 'plan/:work_day', to: 'plan#show'
  get 'newcomers', to: 'newcomers#index'
  get 'system', to: 'system#index'
  get 'janitor', to: 'janitor#index'
  get 'girls/janitor' , to: 'girls#janitor'
  get 'aceess', to: 'aceess#index'
  get 'top', to: 'top#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :girl
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/data_page.rb
class DataPage < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
    
end

app/models/girl.rb
class Girl < ApplicationRecord
    has_many :schedules, -> { order("work_day asc") }
    has_many :options
    has_many :yoyakus
    has_many :bookings
    has_one :tag
    mount_uploader :girl_picture, PictureUploader

    validates :name, presence: true
    validates :age, presence: true
    validates :height, presence: true
    validates :bust, presence: true
    validates :bust_cup, presence: true
    validates :hip, presence: true
    validates :message, presence: true
    validates :tag_a, presence: true
    validates :tag_b, presence: true
    validates :tag_c, presence: true
    validates :tag_d, presence: true
    validates :nomination_fee, presence: true
    validates :start_date, presence: true
    validates :experience, presence: true
    validates :option_id, presence: true





   
end

app/models/kanrisya.rb
class Kanrisya < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/option.rb
class Option < ApplicationRecord
    belongs_to :girl
    has_many :option_lists
    mount_uploader :o_picture, PictureUploader
end

app/models/option_list.rb
class OptionList < ApplicationRecord
    belongs_to :option
    mount_uploader :option_picture, PictureUploader
end

app/models/reserve.rb
class Reserve < ApplicationRecord
    belongs_to :girl
    belongs_to :schedule
    
end

app/models/ryokin.rb
class Ryokin < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    has_many :reserves
    belongs_to :girl

    validates :work_day, presence: true
  validates :start_time, presence: true
  validates :finish_time, presence: true
end

app/models/system.rb
class System < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    belongs_to :girl,optional: true
end

app/models/use.rb
class Use < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   #devise :database_authenticatable, :registerable,
     #     :recoverable, :rememberable, :validatable
end

app/models/yoyaku.rb
class Yoyaku < ApplicationRecord
belongs_to :girl

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_kanrisya!, only: [:new, :edit, :destroy]
  before_action :set_schedule, only: %i[ show edit update destroy ]

  # GET /schedules or /schedules.json
  def index
    @schedules = Schedule.where("work_day >= ?", Date.today)
   
  end

  # GET /schedules/1 or /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
    @girls = Girl.all
  end

  # GET /schedules/1/edit
  def edit
    @girls = Girl.all
  end

  # POST /schedules or /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

  respond_to do |format|
    if @schedule.save
      format.html { redirect_to schedule_url(@schedule), notice: "Schedule was successfully created." }
      format.json { render :show, status: :created, location: @schedule }
    else
      # バリデーションエラーが発生した場合
      @girls = Girl.all # 関連モデルのデータを再度取得
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @schedule.errors, status: :unprocessable_entity }
    end
  end
end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to schedule_url(@schedule), notice: "Schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url, notice: "Schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:girl_id, :work_day, :start_time, :finish_time)
    end
end

app/helpers/girls_helper.rb
module GirlsHelper
end

app/helpers/plan_helper.rb
module PlanHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/uses_helper.rb
module UsesHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule) do |form| %>
  <% if schedule.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(schedule.errors.count, "つの項目に") %> 入力に不足があります。以下の項目を直してください。</h2>

      <div class= "d-flex flex-column">
      <ul>
        <% schedule.errors.each do |error| %>
          <li><%= error.full_message %><div></li>
        <% end %>
      </ul>
      </div>
    </div>
  <% end %>

  <div>
    <%= form.label :girl_id, style: "display: block" %>
      <%= form.collection_select(:girl_id, @girls, :id, :name) %>
  </div>

  <div>
    <%= form.label :work_day, style: "display: block" %>
    <%= form.date_field :work_day %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.time_field :start_time %>
  </div>

  <div>
    <%= form.label :finish_time, style: "display: block" %>
    <%= form.time_field :finish_time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/_schedule.html.erb
<div id="<%= dom_id schedule %>">

<p>
    <strong>名前:</strong>
    <%= schedule.girl.name %>
  </p>

  <p>
    <strong>勤務日:</strong>
    <%= schedule.work_day.strftime('%m月%d日') %>
  </p>

  <p>
    <strong>開始時間:</strong>
    <%= schedule.start_time.strftime('%H時%M分') %>
  </p>

  <p>
    <strong>終了時間:</strong>
    <%= schedule.finish_time.strftime('%H時%M分') %>
  </p>

</div>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render "form", schedule: @schedule %>

<br>

<div>
  <%= link_to "Show this schedule", @schedule %> |
  <%= link_to "Back to schedules", schedules_path %>
</div>

app/views/schedules/index.html.erb
<p style="color: green"><%= notice %></p>
<%= stylesheet_link_tag "abcd", :media => "all" %>
<div class="main-container"><h1>Schedules</h1></div>

<%= link_to "出勤を追加する", new_schedule_path %>

<div id="schedules">
  <% @schedules.each do |schedule| %>
    <%= render schedule %>
    <p>
      <%= link_to "スケジュールの編集・削除", schedule %>
    </p>
  <% end %>
</div>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render "form", schedule: @schedule %>
<br>

<div>
  <%= link_to "Back to schedules", schedules_path %>
</div>

app/views/schedules/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @schedule %>

<div>
  <%= link_to "Edit this schedule", edit_schedule_path(@schedule) %> |
  <%= link_to "Back to schedules", schedules_path %>

  <%= button_to "Destroy this schedule", @schedule, method: :delete %>
</div>