config/routes.rb
Rails.application.routes.draw do
  #root 'top#index'
  #root to: redirect('/top/index')
  root to: redirect('/girls')
  devise_for :kanrisyas
  get 'top/index'
  get 'aceess/index'
  resources :users
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :uses
  get 'event_view/index'
  resources :events
  resources :bookings
  resources :contacts, only: [:new, :create]
  get 'contacts/new'
  get 'waittime/index'
  get 'waittime/show'
  resources :yoyakus
  resources :reserves
  get 'system/index'
  resources :ryokins
  resources :systems
  get 'janitor/index'
  get 'newcomers/index'
  get 'plan/index'
  get 'plan/show'
  get 'girls/janitor'
  resources :options
  resources :option_lists
  resources :tags
  resources :schedules
  resources :data_pages
  resources :girls
  get 'contacts', to: 'contacts#new'
  get 'waittime', to: 'waittime#index'
  get 'event_view', to: 'event_view#index'
  get 'plan', to: 'plan#index'
  get 'plan/:work_day', to: 'plan#show'
  get 'newcomers', to: 'newcomers#index'
  get 'system', to: 'system#index'
  get 'janitor', to: 'janitor#index'
  get 'girls/janitor' , to: 'girls#janitor'
  get 'aceess', to: 'aceess#index'
  get 'top', to: 'top#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :girl
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/data_page.rb
class DataPage < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
    
end

app/models/girl.rb
class Girl < ApplicationRecord
    has_many :schedules, -> { order("work_day asc") }
    has_many :options
    has_many :yoyakus
    has_many :bookings
    has_one :tag
    mount_uploader :girl_picture, PictureUploader

    validates :name, presence: true
    validates :age, presence: true
    validates :height, presence: true
    validates :bust, presence: true
    validates :bust_cup, presence: true
    validates :hip, presence: true
    validates :message, presence: true
    validates :tag_a, presence: true
    validates :tag_b, presence: true
    validates :tag_c, presence: true
    validates :tag_d, presence: true
    validates :nomination_fee, presence: true
    validates :start_date, presence: true
    validates :experience, presence: true
    validates :option_id, presence: true





   
end

app/models/kanrisya.rb
class Kanrisya < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/option.rb
class Option < ApplicationRecord
    belongs_to :girl
    has_many :option_lists
    mount_uploader :o_picture, PictureUploader
end

app/models/option_list.rb
class OptionList < ApplicationRecord
    belongs_to :option
    mount_uploader :option_picture, PictureUploader
end

app/models/reserve.rb
class Reserve < ApplicationRecord
    belongs_to :girl
    belongs_to :schedule
    
end

app/models/ryokin.rb
class Ryokin < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    has_many :reserves
    belongs_to :girl

    validates :work_day, presence: true
  validates :start_time, presence: true
  validates :finish_time, presence: true
end

app/models/system.rb
class System < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    belongs_to :girl,optional: true
end

app/models/use.rb
class Use < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   #devise :database_authenticatable, :registerable,
     #     :recoverable, :rememberable, :validatable
end

app/models/yoyaku.rb
class Yoyaku < ApplicationRecord
belongs_to :girl

end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: %i[ show edit update destroy ]

  # GET /options or /options.json
  def index
    @options = Option.all
  end

  # GET /options/1 or /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
    @girls = Girl.all
    @option_lists = OptionList.all 
  end
  # GET /options/1/edit
  def edit
    @girls = Girl.all
    @option_lists = OptionList.all 
  end

  # POST /options or /options.json
  def create
    @option = Option.new(option_params)

    respond_to do |format|
      if @option.save
        format.html { redirect_to option_url(@option), notice: "Option was successfully created." }
        format.json { render :show, status: :created, location: @option }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1 or /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to option_url(@option), notice: "Option was successfully updated." }
        format.json { render :show, status: :ok, location: @option }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1 or /options/1.json
  def destroy
    @option.destroy

    respond_to do |format|
      format.html { redirect_to options_url, notice: "Option was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def option_params
      params.require(:option).permit(:girl_id, :o_name, :o_picture, :o_price)
    end
end

app/helpers/girls_helper.rb
module GirlsHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/plan_helper.rb
module PlanHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/uses_helper.rb
module UsesHelper
end

app/views/options/_form.html.erb
<%= form_with(model: option) do |form| %>
  <% if option.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
        <% option.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :girl_id, style: "display: block" %>
    <%= form.collection_select(:girl_id, @girls, :id, :name) %>
  </div>

  <div>
    <%= form.label :o_name, style: "display: block" %>
    <%= form.collection_select(:o_name, @option_lists, :option_name, :option_name) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/options/_option.html.erb
<div id="<%= dom_id option %>">
  <p>
    <strong>名前:</strong>
    <%= option.girl.name %>
  </p>

  <p>
    <strong>オプション名:</strong>
    <%= option.o_name %>
  </p>
  <% op = OptionList.where(option_name:option.o_name).first %>
  <p>
    <% option.o_picture = op.option_picture %>
    <% option.save %>
  </p>

  <p>
    <strong>オプション価格:</strong>
    <%= option.o_price = op.option_price %>
    <% option.save %>
  </p>

</div>

app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render "form", option: @option %>

<br>

<div>
  <%= link_to "Show this option", @option %> |
  <%= link_to "Back to options", options_path %>
</div>

app/views/options/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Options</h1>

<%= link_to "新規作成", new_option_path %>

<div id="options">
  <% @options.each do |option| %>
    <%= render option %>
    <p>
      <%= link_to "削除", option %>
    </p>
  <% end %>
</div>

app/views/options/new.html.erb
<h1>New option</h1>

<%= render "form", option: @option %>

<br>

<div>
  <%= link_to "Back to options", options_path %>
</div>

app/views/options/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @option %>

<div>
  <% link_to "Edit this option", edit_option_path(@option) %> 
  <%= link_to "一覧に戻る", options_path %>

  <%= button_to "Destroy this option", @option, method: :delete %>
</div>