config/routes.rb
Rails.application.routes.draw do
  #root 'top#index'
  #root to: redirect('/top/index')
  root to: redirect('/girls')
  devise_for :kanrisyas
  get 'top/index'
  get 'aceess/index'
  resources :users
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :uses
  get 'event_view/index'
  resources :events
  resources :bookings
  resources :contacts, only: [:new, :create]
  get 'contacts/new'
  get 'waittime/index'
  get 'waittime/show'
  resources :yoyakus
  resources :reserves
  get 'system/index'
  resources :ryokins
  resources :systems
  get 'janitor/index'
  get 'newcomers/index'
  get 'plan/index'
  get 'plan/show'
  get 'girls/janitor'
  resources :options
  resources :option_lists
  resources :tags
  resources :schedules
  resources :data_pages
  resources :girls
  get 'contacts', to: 'contacts#new'
  get 'waittime', to: 'waittime#index'
  get 'event_view', to: 'event_view#index'
  get 'plan', to: 'plan#index'
  get 'plan/:work_day', to: 'plan#show'
  get 'newcomers', to: 'newcomers#index'
  get 'system', to: 'system#index'
  get 'janitor', to: 'janitor#index'
  get 'girls/janitor' , to: 'girls#janitor'
  get 'aceess', to: 'aceess#index'
  get 'top', to: 'top#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :girl
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/data_page.rb
class DataPage < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
    
end

app/models/girl.rb
class Girl < ApplicationRecord
    has_many :schedules, -> { order("work_day asc") }
    has_many :options
    has_many :yoyakus
    has_many :bookings
    has_one :tag
    mount_uploader :girl_picture, PictureUploader

    validates :name, presence: true
    validates :age, presence: true
    validates :height, presence: true
    validates :bust, presence: true
    validates :bust_cup, presence: true
    validates :hip, presence: true
    validates :message, presence: true
    validates :tag_a, presence: true
    validates :tag_b, presence: true
    validates :tag_c, presence: true
    validates :tag_d, presence: true
    validates :nomination_fee, presence: true
    validates :start_date, presence: true
    validates :experience, presence: true
    validates :option_id, presence: true





   
end

app/models/kanrisya.rb
class Kanrisya < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/option.rb
class Option < ApplicationRecord
    belongs_to :girl
    has_many :option_lists
    mount_uploader :o_picture, PictureUploader
end

app/models/option_list.rb
class OptionList < ApplicationRecord
    belongs_to :option
    mount_uploader :option_picture, PictureUploader
end

app/models/reserve.rb
class Reserve < ApplicationRecord
    belongs_to :girl
    belongs_to :schedule
    
end

app/models/ryokin.rb
class Ryokin < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    has_many :reserves
    belongs_to :girl

    validates :work_day, presence: true
  validates :start_time, presence: true
  validates :finish_time, presence: true
end

app/models/system.rb
class System < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    belongs_to :girl,optional: true
end

app/models/use.rb
class Use < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   #devise :database_authenticatable, :registerable,
     #     :recoverable, :rememberable, :validatable
end

app/models/yoyaku.rb
class Yoyaku < ApplicationRecord
belongs_to :girl

end

app/controllers/option_lists_controller.rb
class OptionListsController < ApplicationController
  before_action :authenticate_kanrisya!, only: [:new, :edit, :destroy]
  before_action :set_option_list, only: %i[ show edit update destroy ]

  # GET /option_lists or /option_lists.json
  def index
    @option_lists = OptionList.all
  end

  # GET /option_lists/1 or /option_lists/1.json
  def show
  end

  # GET /option_lists/new
  def new
    @option_list = OptionList.new
  end

  # GET /option_lists/1/edit
  def edit
  end

  # POST /option_lists or /option_lists.json
  def create
    @option_list = OptionList.new(option_list_params)

    respond_to do |format|
      if @option_list.save
        format.html { redirect_to option_list_url(@option_list), notice: "Option list was successfully created." }
        format.json { render :show, status: :created, location: @option_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @option_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /option_lists/1 or /option_lists/1.json
  def update
    respond_to do |format|
      if @option_list.update(option_list_params)
        format.html { redirect_to option_list_url(@option_list), notice: "Option list was successfully updated." }
        format.json { render :show, status: :ok, location: @option_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @option_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /option_lists/1 or /option_lists/1.json
  def destroy
    @option_list.destroy

    respond_to do |format|
      format.html { redirect_to option_lists_url, notice: "Option list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option_list
      @option_list = OptionList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def option_list_params
      params.require(:option_list).permit(:option_name, :option_picture, :option_price)
    end
end

app/helpers/girls_helper.rb
module GirlsHelper
end

app/helpers/option_lists_helper.rb
module OptionListsHelper
end

app/helpers/plan_helper.rb
module PlanHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/uses_helper.rb
module UsesHelper
end

app/views/option_lists/_form.html.erb
<%= form_with(model: option_list) do |form| %>
  <% if option_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(option_list.errors.count, "error") %> prohibited this option_list from being saved:</h2>

      <ul>
        <% option_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :option_name, style: "display: block" %>
    <%= form.text_field :option_name %>
  </div>

  <div>
    <%= form.label :option_picture, style: "display: block" %>
    <%= form.file_field :option_picture %>
  </div>

  <div>
    <%= form.label :option_price, style: "display: block" %>
    <%= form.number_field :option_price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/option_lists/_option_list.html.erb
<div id="<%= dom_id option_list %>">
  <p>
    <strong>Option name:</strong>
    <%= option_list.option_name %>
  </p>

  <p>
    <strong>Option picture:</strong>
    <%= image_tag(option_list.option_picture_url(:thumb), width:'100%') if option_list.option_picture.present? %>
  </p>

  <p>
    <strong>Option price:</strong>
    <%= option_list.option_price %>
  </p>

</div>

app/views/option_lists/edit.html.erb
<h1>Editing option list</h1>

<%= render "form", option_list: @option_list %>

<br>

<div>
  <%= link_to "Show this option list", @option_list %> |
  <%= link_to "Back to option lists", option_lists_path %>
</div>

app/views/option_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Option lists</h1>

<div id="option_lists">
  <% @option_lists.each do |option_list| %>
    <%= render option_list %>
    <p>
      <%= link_to "Show this option list", option_list %>
    </p>
  <% end %>
</div>

<%= link_to "New option list", new_option_list_path %>

app/views/option_lists/new.html.erb
<h1>New option list</h1>

<%= render "form", option_list: @option_list %>

<br>

<div>
  <%= link_to "Back to option lists", option_lists_path %>
</div>

app/views/option_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @option_list %>

<div>
  <%= link_to "Edit this option list", edit_option_list_path(@option_list) %> |
  <%= link_to "Back to option lists", option_lists_path %>

  <%= button_to "Destroy this option list", @option_list, method: :delete %>
</div>